{"data":[],"error1":"Commands out of sync; you can't run this command now","loggedin":true}